### ISSUE TITLE
External Postgres using cloud proxy on GCE fails (could not retrieve current migrations)

### ISSUE THREAD

**Issue by mikesparr** [Kong/kong-dist-kubernetes#30]
I set up a CloudSQL instance of Postgres 9.6 and added the `gcr.io/cloudsql-docker/gce-proxy:1.11` proxy and necessary configs. The `kong-migration` job file fails with the following errors and no matter what I try, I get same result.

## Error
[postgres error] could not retrieve current migrations: [postgres error] host or service not provided, or not known

## Expected result
migrations to work (they work locally with docker images and run using --link)

## Details
```

Container | Timestamp | Message
-- | -- | --
kong-migration | 2017-11-29T19:52:11.784059105Z | init_worker_by_lua:46: in function <init_worker_by_lua:44>
kong-migration | 2017-11-29T19:52:11.784056965Z | [C]: in function 'xpcall'
kong-migration | 2017-11-29T19:52:11.784054644Z | init_worker_by_lua:39: in function <init_worker_by_lua:37>
kong-migration | 2017-11-29T19:52:11.784052611Z | /usr/local/bin/kong:7: in function 'file_gen'
kong-migration | 2017-11-29T19:52:11.784050178Z | /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
kong-migration | 2017-11-29T19:52:11.784048123Z | [C]: in function 'xpcall'
kong-migration | 2017-11-29T19:52:11.784045495Z | /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
kong-migration | 2017-11-29T19:52:11.784043192Z | /usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: in function 'cmd_exec'
kong-migration | 2017-11-29T19:52:11.784040521Z | [C]: in function 'assert'
kong-migration | 2017-11-29T19:52:11.784038605Z | stack traceback:
kong-migration | 2017-11-29T19:52:11.784036043Z | /usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: [postgres error] could not retrieve current migrations: [postgres error] host or service not provided, or not known
kong-migration | 2017-11-29T19:52:11.784028195Z | Error:
kong-migration | 2017-11-29T19:52:11.784020572Z | 2017/11/29 19:52:11 [verbose] running datastore migrations
kong-migration | 2017-11-29T19:52:11.784018375Z | 2017/11/29 19:52:11 [verbose] prefix in use: /usr/local/kong
kong-migration | 2017-11-29T19:52:11.784016257Z | 2017/11/29 19:52:11 [verbose] no config file, skipping loading
kong-migration | 2017-11-29T19:52:11.784013505Z | 2017/11/29 19:52:11 [verbose] no config file found at /etc/kong.conf
kong-migration | 2017-11-29T19:52:11.784000226Z | 2017/11/29 19:52:11 [verbose] no config file found at /etc/kong/kong.conf
kong-migration | 2017-11-29T19:52:11.783955120Z | 2017/11/29 19:52:11 [verbose] Kong: 0.11.1
cloudsql-proxy | 2017-11-29T19:49:13.630048863Z | 2017/11/29 19:49:13 Ready for new connections
cloudsql-proxy | 2017-11-29T19:49:13.630045428Z | 2017/11/29 19:49:13 Listening on 127.0.0.1:5432 for my-project:us-central1:my-instance-id
cloudsql-proxy | 2017-11-29T19:49:13.630015451Z | 2017/11/29 19:49:13 using credential file for authentication; email=my-client@my-project.iam.gserviceaccount.com
```

The configuration file with additional image is as follows. The cloud sql proxy runs fine but the kong image crashes every time. I thought at first perhaps it needed time for the proxy to connect so I added the `restartPolicy: OnFailure` but that doesn't solve. For some reason the image doesn't recognize the `ENV` configs and cannot find the database, or are the errors telling me something else?

```
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
      - name: kong-migration
        image: kong
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_DATABASE
            value: "postgres"
          - name: KONG_PG_HOST
            value: "127.0.0.1:5432"
          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret-credentials
                key: password
        command: [ "/bin/sh", "-c", "kong migrations up -v" ]
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=my-project:us-central1:my-instance-id=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: my-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: my-instance-credentials
          secret:
            secretName: my-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
      restartPolicy: OnFailure
```

<img width="1153" alt="screenshot 2017-11-29 13 02 54" src="https://user-images.githubusercontent.com/5553105/33396419-ae325966-d505-11e7-99e8-2dbf19b5e190.png">
