### ISSUE TITLE
[Question] Service configuration with Ingress instead of LoadBalancer

### ISSUE THREAD

**Issue by mikesparr** [Kong/kong-dist-kubernetes#32]
In the example `kong_postgress.yaml` file you have 4 load balancers, one for each port for both proxy and admin. If instead I wanted to use an `Ingress` for terminating SSL and routing to the app, is that okay or is there some specific reason I would want 4 load balancers?

## Preferred
 * Ingress (api.mydomain.com w/ static IP)
   * NodePort (kong)
      * Deployment (kong)

I will trial/error but just wondering if by design there is some reason to have 4 separate services for kong and whether they must be LoadBalancer, or whether anyone has used Ingress instead.

**Comment by mikesparr** [comment]
I was able to reduce down to 2 services for admin and proxy, setting as NodePort, and then referencing them via Ingress. Just in case anyone else is interested, here is the service and ingress configs:

**Note** this uses `kube-lego` (lets encrypt) for automatic SSL cert provisioning.

## Services 
```
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
spec:
  type: NodePort
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong  
```

## Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myco-ingress-production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "myco-static"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/service-upstream: "true"
    ingress.kubernetes.io/tls-minimum-version: "1.1"
spec:
  tls:
  - secretName: myco-tls
    hosts:
    - gateway.myco.com
    - testproxy.myco.com
  rules:
  # KONG microservice gateway
  - host: gateway.myco.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: kong-admin
          servicePort: 8001
  # KONG example of how to configure services below
  # for each domain, add another of these and configure /apis/ in gateway API
  - host: testproxy.clienthub.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: kong-proxy
          servicePort: 8000
```
