### ISSUE TITLE
[Ingress] Service configuration with Ingress 404

### ISSUE THREAD

**Issue by zhouyoufa** [Kong/kong-dist-kubernetes#57]
When I deployed kong and only exposed NodePort services for 8000,8001 and routed nginx via Ingress, the gateway access failed

version : kong/0.13.1

Services
---
```yml
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
  labels:
    app: kong
spec:
  selector:
    app: kong
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
```

Ingress
---
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-proxy
  namespace: kong
  labels:
    app: kong
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Host: mobile-dev.dzxwapp.com";
spec:
  rules:
  - host: gateway.dzxwapp.com
    http:
      paths:
      - backend:
          serviceName: kong-proxy
          servicePort: 8000
  tls:
  - hosts:
      - gateway.dzxwapp.com
    secretName: gateway.dzxwapp.com-tls
```

failed request
---
```curl
curl -X "GET" "https://gateway.dzxwapp.com/v1/status" \
     -H 'Host: mobile-dev.dzxwapp.com' 

HTTP/1.1 404 Not Found
Server: nginx/1.13.9
Date: Wed, 02 May 2018 08:34:19 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: close
Strict-Transport-Security: max-age=15724800; includeSubDomains;

default backend - 404
```

success request
---
```curl
curl -X "GET" "http://kong-proxy.kong.svc.cluster.local:8000/v1/status" \
     -H 'Host: mobile-dev.dzxwapp.com' 

HTTP/1.1 403 Forbidden
Date: Wed, 02 May 2018 08:43:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.13.1

{"message":"Invalid authentication credentials"}
````
