### ISSUE TITLE
for kong1.0.0,job doesn't work with using postgres

### ISSUE THREAD

**Issue by Bevisy** [Kong/kong-dist-kubernetes#67]
**original job**  
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
      - name: kong-migration
        image: kong:1.0.0rc3
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: Never
```
